export const Keys = {
    PREFERRED_COLOR_SCHEME: "PREFERRED_COLOR_SCHEME",
    PREFERRED_SIDE_PANEL_VIEW: "PREFERRED_SIDE_PANEL_VIEW",
    CATALOG_SECTION_QUERY_STRING_PREF: "CATALOG_SECTION_QUERY_STRING_PREF"
} as const
